name = "pedrolunet"
main = "./.svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-10-31"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".svelte-kit/output/client"
binding = "ASSETS"
